warehouse/urls.py
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('users/', include('warehouse.users.urls', namespace='users')),
    path('inventory/', include(('warehouse.inventory.urls', 'inventory'), namespace='inventory')),
    path('inbound/', include('warehouse.inbound.urls', namespace='inbound')),
    path('outbound/', include(('warehouse.outbound.urls', 'outbound'), namespace='outbound')),
    path('storage/', include(('warehouse.storage.urls', 'storage'), namespace='storage')),
    path('dashboard-global/', include('warehouse.dashboard_global.urls', namespace='dashboard_global')),
    
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# Catch-all for SPA front-end, placed last to ensure it doesn't catch API and admin paths
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name='index.html'), name='index'),
]

warehouse/users/urls.py
from django.urls import path
from warehouse.users import views


app_name = "users"

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),
    path('users_dashboard/', views.UsersDashboardView.as_view(), name='users_dashboard'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.custom_logout, name='logout'),
    path('register/', views.register, name='register'),
    path('pending-approval/', views.pending_approval, name='pending_approval'),
    path('deny_user/<int:user_id>/', views.deny_user, name='deny_user'),
    path('approve_user/<int:user_id>/', views.approve_user, name='approve_user'),
    path('new-user/password-reset/', views.CustomPasswordResetView.as_view(), name='new_user_password_reset'),
    path('new-user/password-reset/done/', views.PasswordResetDoneView.as_view(), name='new_user_password_reset_done'),
    path('send_password_reset_email/', views.send_password_reset_email, name='send_password_reset_email'),
    path('generate-qr/', views.generate_qr, name='generate_qr'),
    # Add other URL patterns for the demo app here
    # Make sure you add the QR login URL
    path('login-with-qr/<login_token>/', views.login_with_qr, name='login_with_qr'),
]

warehouse/users/models.py
#USER SETUP TO LOGIN
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse
from django.utils import timezone
from django.utils.translation import gettext_lazy as _

from warehouse.users.managers import UserManager # Importing the custom user manager

# Department model

class Department(models.Model):
    department_name = models.CharField(max_length=255)
    location = models.CharField(max_length=255)

    def __str__(self):
        return self.department_name

# Role model

class Role(models.Model):
    # Choices for role titles
    class RoleChoices(models.TextChoices):
        WAREHOUSE_COMMON = "WAREHOUSE_COMMON", _('Warehouse Common')
        GATEHOUSE = "GATEHOUSE", _('Gatehouse')
        RECEPTIONIST = "RECEPTIONIST", _('Receptionist')
        WAREHOUSE_OPERATIVE = "WAREHOUSE_OPERATIVE", _('Warehouse Operative')
        WAREHOUSE_ADMIN = "WAREHOUSE_ADMIN", _('Warehouse Admin')
        WAREHOUSE_TEAM_LEADER = "WAREHOUSE_TEAM_LEADER", _('Warehouse Team Leader')
        WAREHOUSE_MANAGER = "WAREHOUSE_MANAGER", _('Warehouse Manager')
        INVENTORY_ADMIN = "INVENTORY_ADMIN", _('Inventory Admin')
        INVENTORY_TEAM_LEADER = "INVENTORY_TEAM_LEADER", _('Inventory Team Leader')
        INVENTORY_MANAGER = "INVENTORY_MANAGER", _('Inventory Manager')
        OPERATIONAL_MANAGER = "OPERATIONAL_MANAGER", _('Operational Manager')

    role_title = models.CharField(
        max_length=100,
        choices=RoleChoices.choices,
        default=RoleChoices.WAREHOUSE_COMMON,
        verbose_name=_("Role Title")
    )
    role_description = models.TextField(verbose_name=_("Role Description"))

    def __str__(self):
        return self.get_role_title_display()
    
# Custom User model

class User(AbstractUser):
    # One-to-one relationship with Employee model
    employee = models.OneToOneField('Employee', on_delete=models.CASCADE, related_name='user_profile', null=True, blank=True)

    is_approved = models.BooleanField(default=False)

    objects = UserManager()  # Using the custom user manager
    
     # Method to get the absolute URL of the user

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

    def __str__(self):
        if self.employee:
            return f"{self.employee.employee_first_name} {self.employee.employee_last_name} ({self.username})"
        return self.username
    
# Employee model

class Employee(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='employee_profile')  # Adjusted related_name
    employee_first_name = models.CharField(max_length=100)
    employee_last_name = models.CharField(max_length=100)
    employee_street_number = models.CharField(max_length=128)
    employee_street_name = models.CharField(max_length=255)
    employee_city = models.CharField(max_length=255)
    employee_county = models.CharField(max_length=255)
    employee_country = models.CharField(max_length=255)
    employee_post_code = models.CharField(max_length=20, unique=True)
    date_hired = models.DateField(default=timezone.now) 
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, blank=True, related_name='employees')
    photo = models.ImageField(upload_to='employee_photos/', blank=True, null=True)
    
    def __str__(self):
        return f"{self.employee_first_name} {self.employee_last_name}"
    
# EmployeeRole model
    
class EmployeeRole(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE)
    role = models.ForeignKey(Role, on_delete=models.CASCADE)
    assigned_date = models.DateField()  
    

warehouse/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from .models import Employee

User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=15, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_approved = forms.BooleanField(required=False, initial=False, label=_("Approve User"))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'password1', 'password2', 'is_approved')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }

class CustomUserChangeForm(UserChangeForm):
    first_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    last_name = forms.CharField(max_length=100, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class': 'form-control'}))
    phone_number = forms.CharField(max_length=15, required=False, widget=forms.TextInput(attrs={'class': 'form-control'}))
    is_approved = forms.BooleanField(required=False, label=_("Approve User"))

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'phone_number', 'is_approved', 'password')
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
        }

class EmployeeRegistrationForm(forms.ModelForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}))
    photo = forms.ImageField(
        required=False,  # Assuming the photo is optional
        widget=forms.FileInput(attrs={'class': 'form-control'})
    ) 
    

    class Meta:
        model = Employee
        fields = ('employee_first_name', 'employee_last_name', 'employee_street_number', 'employee_street_name',
                  'employee_city', 'employee_county', 'employee_country', 'employee_post_code', 'date_hired', 'role', 'email', 'photo')
        widgets = {
            'employee_first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_street_number': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_street_name': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_city': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_county': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_country': forms.TextInput(attrs={'class': 'form-control'}),
            'employee_post_code': forms.TextInput(attrs={'class': 'form-control'}),
            'date_hired': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'role': forms.Select(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'photo': forms.FileInput(attrs={'class': 'form-control'}),  
            
        }

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Route69 | Smart Inventory System{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    {% block extra_styles %}{% endblock extra_styles %}
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link href="https://bootswatch.com/5/cerulean/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
</head>
<body>

    <main>
        <!-- Main content will be overridden by child templates -->
        {% block content %}
        {% endblock %}
    </main>

    <footer>
        <!-- Footer content -->
        <p>Copyright © {% now "Y" %} E-ITech</p>
    </footer>


    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    {% block extra_scripts %} {% endblock extra_scripts %}

   
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Home | Smart Inventory System{% endblock title %}

{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock extra_styles %}

{% block content %}
<!-- The outer-container centers the message-container -->
<div class="outer-container">
    <!-- The message-container holds and styles the message and button -->
    <div class="message-container">
        <h1 class="fw-light">Track and Manage Your Inventory</h1>
        <p class="fw-light">Revolutionize Your Warehouse Management with Smart Inventory Solutions</p>
        <div>
            <a href="{% url 'users:login' %}" class="btn btn-primary">Get Started Now!</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/login.html
<!-- login.html -->
{% extends 'base.html' %}
{% load static %}

{% block title %}Login | Smart Inventory System{% endblock title %}

{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/login.css' %}?v=2">
<style>
    a > i.fab {
        color: #1DA1F2; /* Twitter color */
        margin-right: 5px; /* Spacing between icon and text */
    }
    a > i.fab.fa-linkedin-in {
        color: #0077B5; /* LinkedIn color */
    }
</style>
{% endblock extra_styles %}

{% block content %}
<div class="container">
    <div class="left-pane" style="background-image: url('{% static 'images/login.jpg' %}');">
    </div>
    <div class="right-pane">

        <form method="post" action="{% url 'users:login' %}" class="login-form">
            {% csrf_token %}
            <div id="login-error" style="display:none;color:red;"></div>
            <div class="form-container"> <!-- Updated container for form fields -->
                <div class="textbox">
                    <input type="text" id="username" name="username" placeholder="Email" required class="form-control" autocomplete="current-username">
                </div>
                <div class="textbox">
                    <input type="password" id="password" name="password" placeholder="Password" required class="form-control" autocomplete="current-password">
                </div>
                <div class="form-group"> <!-- This can stay as is if you want to style the button separately -->
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </div>
            <p>Ready to get started? <a href="{% url 'users:register' %}">Create account</a></p>
            <div class="qr-login">
                <p>Use your phone camera to scan this code to log in instantly</p>
                <img src="{% url 'users:generate_qr' %}" alt="Login with QR Code" style="width: 150px; height: 150px;">
            </div>
        </form>
        <div class="footer">
            <p>
                <a href="https://twitter.com/route69" target="_blank"><i class="fab fa-twitter"></i> Twitter</a> |
                <a href="https://linkedin.com/in/route69" target="_blank"><i class="fab fa-linkedin-in"></i> LinkedIn</a>

            </p>
        </div>
    </div>
</div>
{% endblock content %}

{% block extra_scripts %}
<!-- Load jQuery first -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- Then load your custom AJAX login script -->
<script src="{% static 'js/login.js' %}"></script>
<script src="{% static 'js/badge_status.js' %}"></script>
{% endblock extra_scripts %}

templates/logout.html
{% extends 'base.html' %}

{% load static %}
{% block title %}Logged Out | Smart Inventory System{% endblock title %}
{% block extra_styles %}
<link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock extra_styles %}

{% block content %}
<div class="outer-container">
    <div class="message-container">
        <h1 class="fw-light">You Have Been Logged Out</h1>
        <p class="fw-light">You can log in again to continue managing your inventory.</p>
        <div>
            <a href="{% url 'users:home' %}" class="btn btn-primary">Log In Again</a>
        </div>
    </div>
</div>
{% endblock content %}

templates/register.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Register | Smart Inventory System{% endblock title %}
{% block extrahead %}
{% block extra_styles %}
   <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock extra_styles %}
{% endblock %}
{% block content %}
<div class="register-page">
    <div class="register-container">
        <h2 class="text-center">Register</h2>
        <form method="post" enctype="multipart/form-data" novalidate>
            {% csrf_token %}

            <!-- Display non-field errors that aren't associated with a specific field -->
            {% if form.non_field_errors %}
                <div class="errorlist">
                    {% for error in form.non_field_errors %}
                        <p style="color: red">{{ error }}</p>
                    {% endfor %}
                </div>
            {% endif %}

            <!-- Fields grouped by rows -->
            <div class="form-row">
                <div class="form-field">
                    <label for="id_employee_first_name">Employee first name:</label>
                    <input type="text" name="employee_first_name" class="form-control" maxlength="100" required id="id_employee_first_name" autofocus>
                    {% for error in form.employee_first_name.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-field">
                    <label for="id_employee_last_name">Employee last name:</label>
                    <input type="text" name="employee_last_name" class="form-control" maxlength="100" required id="id_employee_last_name">
                    {% for error in form.employee_last_name.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-row">
                <div class="form-field">
                    <label for="id_employee_street_number">Employee street number:</label>
                    <input type="text" name="employee_street_number" class="form-control" maxlength="128" required id="id_employee_street_number">
                    {% for error in form.employee_street_number.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-field">
                    <label for="id_employee_street_name">Employee street name:</label>
                    <input type="text" name="employee_street_name" class="form-control" maxlength="255" required id="id_employee_street_name">
                    {% for error in form.employee_street_name.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-row">
                <div class="form-field">
                    <label for="id_employee_city">Employee city:</label>
                    <input type="text" name="employee_city" class="form-control" maxlength="255" required id="id_employee_city">
                    {% for error in form.employee_city.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-field">
                    <label for="id_employee_county">Employee county:</label>
                    <input type="text" name="employee_county" class="form-control" maxlength="255" required id="id_employee_county">
                    {% for error in form.employee_county.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-row">
                <div class="form-field">
                    <label for="id_employee_country">Employee country:</label>
                    <input type="text" name="employee_country" class="form-control" maxlength="255" required id="id_employee_country">
                    {% for error in form.employee_country.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-field">
                    <label for="id_employee_post_code">Employee post code:</label>
                    <input type="text" name="employee_post_code" class="form-control" maxlength="20" required id="id_employee_post_code">
                    {% for error in form.employee_post_code.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-row">
                <div class="form-field">
                    <label for="id_date_hired">Date hired:</label>
                    <input type="date" name="date_hired" class="form-control" required id="id_date_hired" value="2024-04-20">
                    {% for error in form.date_hired.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-field">
                    <label for="id_role">Role:</label>
                    <select name="role" class="form-control" id="id_role">
                        <option value="" selected>---------</option>
                            <option value="1">Warehouse Common</option>
                            <option value="2">Gatehouse</option>
                            <option value="3">Receptionist</option>
                            <option value="4">Warehouse Operative</option>
                            <option value="5">Warehouse Admin</option>
                            <option value="6">Warehouse Team Leader</option>
                            <option value="7">Warehouse Manager</option>
                            <option value="8">Inventory Admin</option>
                            <option value="9">Inventory Team Leader</option>
                            <option value="10">Inventory Manager</option>
                            <option value="11">Operational Manager</option>
                    </select>
                    {% for error in form.role.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
            </div>

            <div class="form-row">
                <div class="form-field">
                    <label for="id_email">Email:</label>
                    <input type="email" name="email" class="form-control" maxlength="320" required id="id_email">
                    {% for error in form.email.errors %}
                        <div style="color: red">{{ error }}</div>
                    {% endfor %}
                </div>
                <div class="form-field">
                    <label for="id_photo">Photo:</label>
                    <input type="file" name="photo" class="form-control" id="id_photo">
                </div>
            </div>

            <!-- Terms and Conditions Checkbox -->
            <div class="form-row text-center">
                <div class="form-field checkbox-group">
                    <input type="checkbox" id="terms" name="terms" required>
                    <label for="terms">By signing up, I agree with the Terms of Use & Privacy Policy</label>
                </div>
            </div>

            <!-- Submit Button -->
            <div class="form-row">
                <div class="form-field">
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </div>

            <!-- Login Link -->
            <div class="form-row text-center login-link">
                Already have an account? <a href="{% url 'users:login' %}">Please Login</a>
            </div>
        </form>
    </div>
</div>

{% endblock %}