warehouse/dashboard_global/urls.py
from django.urls import path
from .views import dashboard_view, profile_view, reports_view, settings_view, logout_view

app_name = 'dashboard_global'

urlpatterns = [
    path('dashboard/', dashboard_view, name='dashboard'),
    path('profile/', profile_view, name='profile'),
    path('reports/', reports_view, name='reports'),
    path('settings/', settings_view, name='settings'),
    path('logout/', logout_view, name='logout'),
    
    
]

warehouse/inbound/urls.py
from django.urls import path

from .views import (
    FinalBayAssignmentListView,
    GatehouseLogView,
    InboundDashboardView,
    ProvisionalBayAssignmentCreateView,
    ProvisionalBayAssignmentListView,
    register_booking
)

app_name='Inbound'

urlpatterns = [
    
    path('dashboard/', InboundDashboardView.as_view(), name='inbound_dashboard'),
    path('gatehouse-log/', GatehouseLogView.as_view(), name='gatehouse_log'),
    path('register-booking/', register_booking, name='register_booking'),
    path('provisional-bay-assignments/', ProvisionalBayAssignmentListView.as_view(), name='provisional_bay_assignments'),
    path('create-provisional-bay-assignment/', ProvisionalBayAssignmentCreateView.as_view(), name='create_provisional_bay_assignment'),
    path('final-bay-assignments/', FinalBayAssignmentListView.as_view(), name='final_bay_assignments'),
   
    
    
]

warehouse/inventory/urls.py
from django.urls import path
from . import views

app_name= 'inventory'

urlpatterns = [
   
    path('dashboard/', views.InventoryDashboardView.as_view(), name='inventory_dashboard'),
    # Categories URLS
    path('categories/', views.category_list, name='category_list'),
    path('add_category/', views.add_category, name='add_category'),
     # Product URLS
    path('products/new/', views.FoodProductCreateView.as_view(), name='food_product_create'),
    path('products/edit/redirect/', views.ProductEditRedirectView.as_view(), name='food_product_edit_redirect'),
    path('products/<int:pk>/edit/', views.FoodProductUpdateView.as_view(), name='food_product_edit'),
    path('products/delete/redirect/', views.ProductDeleteRedirectView.as_view(), name='food_product_delete_redirect'),
    path('products/<int:pk>/delete/', views.FoodProductConfirmDeleteView.as_view(), name='food_product_confirm_delete'),
    path('product/<int:pk>/delete/', views.product_delete, name='product_delete'),
    path('search/', views.search_results, name='inventory_search_results'),
    path('product/<int:pk>/details/', views.sku_details, name='product_detail'),
    
    # Supplier URLS
    path('suppliers_dashboard/', views.SuppliersDashboardView.as_view(), name='suppliers_dashboard'),
    path('suppliers/', views.SupplierListView.as_view(), name='supplier-list'),
    path('suppliers/add/', views.SupplierCreateUpdateView.as_view(), name='supplier-add'),  # Create
    path('suppliers/<int:pk>/edit/', views.SupplierCreateUpdateView.as_view(), name='supplier-update'),  # Update
    path('suppliers/<int:pk>/delete/', views.SupplierDeleteView.as_view(), name='supplier-delete'),  # Delete
    
    #Audit Log URL
     path('audit-logs/', views.audit_log_list, name='audit_log_list'),
     
    #Stock Level URLS
    path('stock/dashboard/', views.StockLevelDashboardView.as_view(), name='stock_level_dashboard'),
    path('stock/levels/', views.StockLevelListView.as_view(), name='stock_level_list'),
    path('stock_level_create/', views.create_stock_level, name='stock_level_create'),
    path('update-stock/<int:stock_id>/', views.update_stock, name='update-stock'),
    path('stock/levels/<int:pk>/delete/', views.StockLevelDeleteView.as_view(), name='stock_level_delete'),
    path('dashboard/', views.stock_level_dashboard, name='stock_dashboard'),
    path('generate_pie_counts/', views.generate_pie_counts_from_pdf, name='generate_pie_counts_from_pdf'),
    
    #Transaction URLS
    
    path('transactions/', views.transaction_list, name='transaction_list'),
    path('transactions/<int:transaction_id>/', views.transaction_detail, name='transaction_detail'),
    
    #Reports
    path('reports/', views.reports_view, name='reports'),
    path('report-list/', views.report_list_view, name='report-list'),
    path('report-detail/<int:report_id>/', views.report_detail_view, name='report-detail'),
]

warehouse/urls.py
from django.urls import path, re_path, include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    
    path('users/', include('warehouse.users.urls', namespace='users')),
    path('inventory/', include(('warehouse.inventory.urls', 'inventory'), namespace='inventory')),
    path('inbound/', include('warehouse.inbound.urls', namespace='inbound')),
    path('outbound/', include(('warehouse.outbound.urls', 'outbound'), namespace='outbound')),
    path('storage/', include(('warehouse.storage.urls', 'storage'), namespace='storage')),
    path('dashboard-global/', include('warehouse.dashboard_global.urls', namespace='dashboard_global')),
    
]

# Serve static and media files in development
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

# Catch-all for SPA front-end, placed last to ensure it doesn't catch API and admin paths
urlpatterns += [
    re_path(r'^.*$', TemplateView.as_view(template_name='index.html'), name='index'),
]

warehouse/dashboard_global/models.py
# models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.db.models.signals import post_save
from django.dispatch import receiver

User = get_user_model()

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='user_photos')
    role = models.CharField(max_length=100, default='User')

    def __str__(self):
        return f"{self.user.username} ({self.role})"

@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        instance.profile.save()

warehouse/outbound/models.py
import logging
from django.db import models
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import get_user_model
from simple_history.models import HistoricalRecords
from django.core.exceptions import ValidationError
from django.utils import timezone
from warehouse.storage.models import Location




User = get_user_model()


class Outbound(Location):  
    address = models.CharField(max_length=255, null=True)
    floor_number = models.PositiveIntegerField()
    bay_number = models.PositiveIntegerField()
    additional_info = models.TextField()
    location_identifier = models.CharField(max_length=100)
    max_capacity = models.IntegerField()
    operational_restrictions = models.CharField(max_length=255)
    special_handling_required = models.BooleanField(default=False)
    history = HistoricalRecords()
    outbound_code = models.CharField(max_length=50, unique=True, verbose_name=_("Outbound Code"))
    related_outbounds = models.ManyToManyField('self', symmetrical=False, blank=True, verbose_name=_("Related Outbounds"))
    managing_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='managed_outbounds', verbose_name=_("Managing User"))
    utilized_capacity = models.PositiveIntegerField(default=0, verbose_name=_("Utilized Capacity"))

    def __str__(self):
        return f"{self.outbound_code} - Floor {self.floor_number} - Bay {self.bay_number}"

    @staticmethod
    def get_default_location():
        unique_criteria = {
            'outbound_code': 'DEFAULT_OUTBOUND',  # Ensuring unique code for default location
            'location_identifier': 'DEFAULT_OUTBOUND'  # Assuming 'location_identifier' needs to be unique as well
        }
        default_location, _ = Outbound.objects.get_or_create(
            defaults={
                'address': 'Default Address',
                'floor_number': 1,
                'bay_number': 1,
                'additional_info': 'Default outbound location',
                'max_capacity': 1000,
                'operational_restrictions': 'None',
                'special_handling_required': False,
                'utilized_capacity': 0
            },
            **unique_criteria
        )
        return default_location




# LLOP TASK MODEL

class LLOPTask(models.Model):
    TASK_CHOICES = [
        ('Picking', _('Picking')),
        ('Replenishing', _('Replenishing')),
    ]

    task_type = models.CharField(
        max_length=20, 
        choices=TASK_CHOICES, 
        default='Picking', 
        help_text=_("Type of LLOP task.")
    )
    product = models.ForeignKey(
        'inventory.FoodProduct', 
        on_delete=models.CASCADE, 
        related_name='llop_tasks', 
        verbose_name=_("Product")
    )
    source_location = models.ForeignKey(
        'storage.PickFace', 
        on_delete=models.CASCADE, 
        related_name='llop_source_tasks', 
        verbose_name=_("Source Location")
    )
    destination_location = models.ForeignKey(
        'Outbound',  # Directly using Outbound which is a specialized Location
        on_delete=models.CASCADE, 
        related_name='llop_destination_tasks', 
        verbose_name=_("Destination Location")
    )
    quantity = models.PositiveIntegerField(verbose_name=_("Quantity"))
    unit_price = models.DecimalField(
        max_digits=8, 
        decimal_places=2,
        help_text=_("Unit price at the time of task creation")
    )
    assigned_to = models.ForeignKey(
        User, 
        on_delete=models.SET_NULL, 
        null=True, 
        blank=True, 
        related_name='assigned_llop_tasks', 
        verbose_name=_("Assigned To")
    )
    status = models.CharField(
        max_length=20, 
        choices=[('Assigned', _('Assigned')), ('In Progress', _('In Progress')), ('Completed', _('Completed'))], 
        default='Assigned', 
        verbose_name=_("Status")
    )
    start_time = models.DateTimeField(
        auto_now_add=True, 
        verbose_name=_("Start Time")
    )
    completion_time = models.DateTimeField(
        null=True, 
        blank=True, 
        verbose_name=_("Completion Time")
    )
    history = HistoricalRecords()

    def __str__(self):
        return f"{self.get_task_type_display()} Task for {self.product.name} - {self.quantity} units from {self.source_location} to {self.destination_location}"

    def perform_task(self):
        if self.status != 'Assigned':
            return "Task is already started or completed."
        self.status = 'In Progress'
        self.save()

        if self.source_location.current_stock < self.quantity:
            raise ValueError("Insufficient stock at source.")

        self.source_location.current_stock -= self.quantity
        self.source_location.save()

        destination_stock, _ = 'inventory.StockLevel'.objects.get_or_create(
        location=self.destination_location, product=self.product, defaults={'quantity': 0})
        destination_stock.quantity += self.quantity
        destination_stock.save()

        self.status = 'Completed'
        self.completion_time = timezone.now()
        self.save()
        return "Task completed."

    def __str__(self):
        return f"{self.get_task_type_display()} - {self.product.name} from {self.source_location} to {self.destination_location}"

    def update_stock_levels(self):
        """Adjust stock levels at source and destination based on the task."""
        if self.source_location.current_stock < self.quantity:
            raise ValueError("Insufficient stock at source location to perform the task.")

        self.source_location.current_stock -= self.quantity
        self.source_location.save()

        destination_stock, created = 'inventory.StockLevel'.objects.get_or_create(
            location=self.destination_location,
            product=self.product,
            defaults={'quantity': 0}
        )
        destination_stock.quantity += self.quantity
        destination_stock.save()
        
# VNA TASKS
        
class VNATask(models.Model):
    TASK_TYPES = [
        ('Putaway', 'Putaway from PND to Storage'),
        ('Order Picking', 'Order Picking from Storage to PND'),
        ('Replenishment Picking', 'Replenishment Picking from Storage to PND')
    ]

    task_type = models.CharField(
        max_length=30,
        choices=TASK_TYPES, 
        default='Putaway',
        help_text=_("Type of VNA task.")
    )
    product = models.ForeignKey('inventory.FoodProduct', on_delete=models.CASCADE, related_name='vna_tasks', verbose_name=_("Product"))
    quantity = models.PositiveIntegerField(verbose_name=_("Quantity"))
    source_location = models.ForeignKey('storage.Location', on_delete=models.CASCADE, related_name='vna_source_tasks', verbose_name=_("Source Location"))
    destination_location = models.ForeignKey('storage.Location', on_delete=models.CASCADE, related_name='vna_destination_tasks', verbose_name=_("Destination Location"))
    vna_equipment = models.CharField(max_length=255, verbose_name=_("VNA Equipment"), help_text=_("The VNA equipment used for this task."))
    status = models.CharField(
        max_length=20, 
        choices=[
            ('Assigned', 'Assigned'), 
            ('In Progress', 'In Progress'), 
            ('Completed', 'Completed')
        ], 
        default='Assigned', 
        verbose_name=_("Status")
    )
    start_time = models.DateTimeField(auto_now_add=True, verbose_name=_("Start Time"))
    completion_time = models.DateTimeField(null=True, blank=True, verbose_name=_("Completion Time"))
    notes = models.TextField(blank=True, null=True, verbose_name=_("Notes"))
    history = HistoricalRecords()

    class Meta:
        verbose_name = _("VNATask")
        verbose_name_plural = _("VNATasks")

    def __str__(self):
        task_type_display = dict(self.TASK_TYPES).get(self.task_type, "Unknown Task Type")
        return f"{task_type_display} for {self.product.name} from {self.source_location} to {self.destination_location} - {self.status}"

    def save(self, *args, **kwargs):
        creating = not self.pk  # Check if the object is being created
        if self.task_type == 'Putaway' and self.source_location.type != 'PND':
            raise ValidationError("Source location must be a PND type for Putaway tasks.")
        elif self.task_type in ['Order Picking', 'Replenishment Picking'] and self.destination_location.type != 'PND':
            raise ValidationError("Destination location must be a PND type for Picking tasks.")
        
        super().save(*args, **kwargs)  # Call the "real" save method.
        
        if creating and self.status == 'Completed' and self.task_type == 'Order Picking':
            # Assuming FLTTask and Outbound models are defined with a get_default_location method
            'inbound.FLTTask'.objects.create(
                task_type='Order Completion',
                product=self.product,
                quantity=self.quantity,
                source_location=self.destination_location,
                destination_location='outboundOutbound'.get_default_location(),
                status='Pending'
            )
    
logger = logging.getLogger(__name__)
    
class ReplenishmentTask(models.Model):
    source_location = models.ForeignKey('storage.Location', on_delete=models.CASCADE, related_name='replenishment_sources')
    destination_location = models.ForeignKey('storage.Location', null=True, on_delete=models.CASCADE, related_name='replenishment_destinations')
    product = models.ForeignKey('inventory.FoodProduct', on_delete=models.CASCADE, related_name='replenishment_tasks')
    quantity = models.PositiveIntegerField(help_text=_("Quantity to be replenished."))
    status = models.CharField(max_length=20, choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Pending')
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name='replenishment_tasks')

warehouse/dashboard_global/templates/base_dashboard.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/dashboard_global.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Route69 | Smart Inventory System{% endblock %}</title>
    <link rel="icon" type="image/x-icon" href="{% static 'favicon/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link href="https://bootswatch.com/5/cerulean/bootstrap.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <body class="d-flex flex-column min-vh-100">
        <div class="container-fluid flex-grow-1">
            <div class="row">
            <!-- Sidebar -->
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                <div class="sidebar-logo-container">
                    <img src="{% static 'images/FullLogo.png' %}" alt="Full Logo" class="sidebar-logo"> <!-- Notice the 'sidebar-logo' class here -->
                </div>
                <div class="user-profile-container">
                    <!-- User avatar image -->
                    {% if request.user.profile.photo %}
                        <img src="{{ request.user.profile.photo.url }}" alt="{{ request.user.get_full_name }}" class="profile-avatar">
                    {% else %}
                        <img src="{% static 'images/users/Warehouse Manager.jpg' %}" alt="Default Avatar" class="profile-avatar">
                    {% endif %}
                    <span class="profile-name">{{ request.user.get_full_name }}</span>
                </div>                              
                <div class="sidebar-sticky">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" href="/">
                                <span class="icon-container">
                                <img src="{% static 'icons/dashboard-icon.png' %}" alt="Dashboard" class="nav-icon">
                            </span>
                                Dashboard 
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inbound:inbound_dashboard' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/dashboard-icon.png' %}" alt="Inbound">
                                </span>
                                Inbound
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard_global:dashboard' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/dashboard-icon.png' %}" alt="Outbound">
                                </span>
                                Outbound
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inventory:inventory_dashboard' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/dashboard-icon.png' %}" alt="Inventory">
                                </span>
                                Inventory
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'storage:storage_dashboard' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/storage.png' %}" alt="Storage">
                                </span>
                                Storage
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'inventory:reports' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/reports.png' %}" alt="Reports">
                                </span>
                                Reports
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard_global:settings' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/settings.png' %}" alt="Settings">
                                </span>
                                Settings
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'dashboard_global:logout' %}">
                                <span class="icon-container">
                                    <img src="{% static 'icons/logout.png' %}" alt="Logout">
                                </span>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </nav>

            <!-- Main content -->
            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                {% block content %}{% endblock %}
            </main>
        </div>
    <footer class="text-muted py-4 bg-light mt-auto">
        <div class="container">
            <p class="float-right">
                <a href="#">Back to top</a>
            </p>
            <p>Copyright © {% now "Y" %} E-ITech</p>
        </div>
    </footer>
    <!-- Bootstrap JS, Popper.js, and jQuery -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.2/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>